version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  initairflow:
    image: apache/airflow:1.10.12
    container_name: "airflow-initdb"
    entrypoint: ./scripts/init.sh
    volumes:
      - ./scripts:/opt/airflow/scripts
    env_file:
      - .envvars
    depends_on:
      - postgres

  scheduler:
    image: apache/airflow:1.10.12-python3.7
    command: scheduler
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    depends_on:
      - initairflow
    env_file:
      - .envvars
    volumes:
      - ../dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./kubeconfig/config:/home/airflow/.kube/config
      - ./kubeconfig/ca.crt:/home/airflow/.kube/ca.crt
      - ./kubeconfig/client.crt:/home/airflow/.kube/client.crt
      - ./kubeconfig/client.key:/home/airflow/.kube/client.key

  webserver:
    image: apache/airflow:1.10.12-python3.7
    command: webserver
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    depends_on:
      - initairflow
      - scheduler
    env_file:
      - .envvars
    volumes:
      - ../dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"

  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - ./data/minio:/data:delegated
    ports:
      - 9000:9000
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

