---
apiVersion: v1
kind: ConfigMap
metadata:
  name: small-cluster
  labels:
    name: spark
data:
  spark-ceph.conf: |
    spark.app.name=small-cluster
    spark.kubernetes.container.image=ferlabcrsj/spark:3.1.2
    spark.sql.shuffle.partitions=500
    spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
    spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
    spark.executor.instances=1
    spark.executor.memory=24g
    spark.executor.cores=2
