name: Test Pipeline

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Init airflow db
        run: airflow db init
      - name: Run non-vpn unit tests
        run: pytest -m "not vpn"